### ISSUE TITLE
Textile Editor (Link Auto–Formatting Deletes Line–Breaks)

### ISSUE THREAD

**Issue by chang-zhao** [tovic/text-editor#5]
Be healthy, Taufik!

**Textile demo**
https://rawgit.com/tovic/text-editor/master/text-editor/ui/textile/index.html

When I select a text starting from the beginning of the line, and add a link (with the editor icon), the result is that the link is created OK, but it moves to the end of the preceding string. BReaks disappear. Even if there are 2 breaks, so that should be the next paragraph.

Also, **UI Demo** some Fam Fam Fam icons are missing?
https://rawgit.com/tovic/text-editor/master/text-editor/ui/index.html

**Offtopic:**
I'm experimenting with writing my own **Wiki / CMS**.

I think it's better to use some DB than text files, because I use DokuWiki (my favorite), and it has a few inconveniences:

1. UTF-8 (non-latin) names of folders and files not shown correctly in Windows file manager (at least up to Windows 7), so there is no convenience to have a structure in real folders. (I don't like to use Total Commander).

2. Search becomes slow when the pages amount grows over some 10000 or 20000. So the plain text files become limitation. The developers use indexing with DB, but still DokuWiki doesn't suit very large projects. Which is a shame, because it's very good - IMHO better than MediaWiki; so it could be world leading wiki now, if not limitation set by design choice many years ago.

There is SQLite now that keeps all DB in one convenient file, so I think it's the best choice for a CMS.

I'm trying to use, so far so good, and I plan to integrate it with Sphinx search engine. It seems to be lightweight and with a good support for language morphology.

A question **about editors**:
I enjoy your works.
Would you recommend to try to use your editor?
I use CKE, but like to try something else, light and simple and not causing problems.

Is your work still in progress (not finished for usage)?
Is it easy to use for a dabbler like me?

What would you recommend?

I'd like to have markup, but also to paste some pieces of html from elsewhere.
Is it possible and reasonable to make markup in html text?
Like `<p>Words *bold* and so on </p>`.

Thank you, excuse me for a lengthy offtopic. I didn't want to split our talk to several pieces everywhere :).

Good luck for you and your friends and relatives!

**Comment by tovic** [comment]
> Be healthy, Taufik!

Thanks.

> When I select a text starting from the beginning of the line, and add a link (with the editor icon), the result is that the link is created OK, but it moves to the end of the preceding string. BReaks disappear. Even if there are 2 breaks, so that should be the next paragraph.

Currently that is the desired behaviour. Headers and span elements will automatically remove line&ndash;breaks in selection [1](https://github.com/tovic/text-editor/blob/3a190919e4cfffe60166c82f8cd328ca4ad50fd6/text-editor/ui/ui.js#L615&L618), [2](https://github.com/tovic/text-editor/blob/78651339c43061744bf4160500a9d3d7d6cbd5a0/text-editor/ui/html/html.js#L214&L216) and replace any white&ndash;spaces before and after selection with a single space [1](https://github.com/tovic/text-editor/blob/3a190919e4cfffe60166c82f8cd328ca4ad50fd6/text-editor/ui/ui.js#L607&L613) [2](https://rawgit.com/tovic/text-editor/ae3025c1bfa48076cfc0fb487748313cc59bb523/test.html) &rarr; look at _force a space before and after caret/selection_ and _force line-break before and after caret/selection_ button

> Also, UI Demo some Fam Fam Fam icons are missing?

No. I just don&rsquo;t add support for all of the **Font Awesome** icon sample tools. The current update fix the missing icons.

> Would you recommend to try to use your editor?

Yes. I make something to be used by others.

> Is your work still in progress (not finished for usage)?

The API is mature enough. Just need to standardize the existing attitude in handling some unusual possibilities (like in your case). I am currently focus on making a better documentation page &rarr; <https://tovic.github.io/text-editor>

> Is it easy to use for a dabbler like me?
> What would you recommend?

Depends. Probably we need a plugin developer for specific CMS to create simpler function wrapper to automaticize everything.

> I&rsquo;d like to have markup, but also to paste some pieces of HTML from elsewhere. Is it possible and reasonable to make markup in HTML text?

Personally, custom markup than can be accepted by me should have building structure just like the HTML itself. Something like _shortcodes_:

~~~ .twig
{{fo bar="baz"}}qux{{/foo}}
~~~

---

> I think it&rsquo;s better to use some DB than text files.

It depends on the needs and key objectives. I personally prefer [database&ndash;less CMS](https://github.com/tovic/cms-starter) because I only need the function to view the page, with pretty URL, that&rsquo;s it. With the main advantages that it can be downloaded and uploaded easily without the need for extra settings. As easy as uploading any static files.
